#!/usr/bin/env python3
"""
GLUE Framework CLI

A command-line interface for the GenAI Linking & Unification Engine
(GLUE) framework, which provides tools for working with multi-model
AI applications with features like adhesive tool bindings and
magnetic information flow.
"""
import os
import sys
import json
import asyncio
import argparse
import logging
import re
import uuid
from pathlib import Path
from typing import List, Dict, Any, Optional, Union
from rich import print
from rich.console import Console
from rich.syntax import Syntax
from rich.prompt import Prompt

# Import framework modules
# Use direct imports to avoid circular imports
from glue.core.app import GlueApp
from glue.core.types import AdhesiveType
from glue.core.agent_loop import AgentLoop, AgentState
from glue.core.teams import Team
from glue.dsl import GlueDSLParser, GlueLexer
from glue.tools import SimpleBaseTool, register_tool

# Import from cliHelpers for backward compatibility with tests
from glue.cliHelpers import (
    colorize_agent_output,
    format_agent_message,
    parse_interactive_command,
    get_interactive_help_text,
    format_agent_interactions
)

# Import new utilities
from .utils.json_utils import extract_json

# Constants for tools
AVAILABLE_TOOLS = {
    "web_search": {
        "description": "Search the web for information",
        "parameters": {"query": "string"}
    },
    "file_handler": {
        "description": "Read and write files",
        "parameters": {"path": "string", "content": "string (optional)"}
    },
    "code_interpreter": {
        "description": "Execute Python code",
        "parameters": {"code": "string"}
    },
    "communicate": {
        "description": "Communicate with other models or teams",
        "parameters": {"target_type": "string", "target_name": "string", "message": "string"}
    }
}

# Version information
__version__ = "0.1.0-alpha"  # Updated for alpha release

# Constants
DEFAULT_ENV_FILE = ".env"
CONFIG_DIR = os.path.expanduser("~/.glue")
LOGS_DIR = os.path.join(CONFIG_DIR, "logs")
TEMPLATES_DIR = os.path.join(CONFIG_DIR, "templates")

# Helper functions for formatting and display
def format_component_name(name: str, component_type: str = "component") -> tuple:
    """Format a component name for display.
    
    Args:
        name: Name of the component
        component_type: Type of component (e.g., "tool", "model", "team")
        
    Returns:
        Tuple of (directory_name, module_name, class_name)
    """
    # Convert to lowercase and handle spaces
    name_lower = name.lower()
    
    # Directory name uses hyphens
    dir_name = name_lower.replace(" ", "-")
    
    # Module name uses underscores
    module_name = name_lower.replace(" ", "_")
    
    # Class name is CamelCase
    class_name = "".join(word.capitalize() for word in name_lower.split())
    
    return dir_name, module_name, class_name

# ==================== Application Functions ====================
async def run_app(config_file: str, mode: str = "non-interactive", input_text: str = None) -> bool:
    """Run a GLUE application from a configuration file.
    
    Args:
        config_file: Path to the GLUE configuration file
        mode: Execution mode ("interactive" or "non-interactive")
        input_text: Input text to process (for non-interactive mode)
        
    Returns:
        True if successful, False otherwise
    """
    logger = logging.getLogger("glue.run_app")
    console = Console()
    
    try:
        # Check if file exists
        if not os.path.exists(config_file):
            logger.error(f"Configuration file not found: {config_file}")
            print(f"Error: Configuration file not found: {config_file}")
            return False
        
        logger.info(f"Parsing GLUE file: {config_file}")
        
        # Read the GLUE file
        with open(config_file, 'r') as f:
            glue_content = f.read()
        
        # Create lexer and parser
        lexer = GlueLexer()
        parser = GlueDSLParser()
        
        # Parse the GLUE file
        tokens = lexer.tokenize(glue_content)
        
        # Only print tokens in debug mode
        if logger.level == logging.DEBUG:
            logger.debug("Tokens generated by lexer:")
            for token in tokens:
                logger.debug(f"  {token.type}: '{token.value}' at line {token.line}")
        
        # Parse tokens into AST
        logger.info("Parsing tokens into AST")
        ast = parser.parse(tokens)
        
        # Check if Portkey integration is enabled
        portkey_enabled = False
        portkey_api_key = None
        
        # Check for Portkey configuration in the AST
        if "app" in ast and "config" in ast["app"]:
            app_config = ast["app"]["config"]
            if isinstance(app_config, dict) and "portkey" in app_config and app_config["portkey"]:
                portkey_enabled = True
        
        # If Portkey is enabled, check for API key
        if portkey_enabled:
            logger.info("Portkey integration is enabled")
            portkey_api_key = os.environ.get("PORTKEY_API_KEY")
            if not portkey_api_key:
                logger.warning("Portkey API key not found in environment variables")
                print("Warning: Portkey is enabled but PORTKEY_API_KEY is not set in environment variables")
            else:
                logger.info("Portkey API key found")
                # Configure Portkey here (implementation depends on how Portkey is integrated)
        
        # Build the application
        logger.info("Building GLUE application")
        
        # Create a new GlueApp instance with the parsed config and mode
        app = GlueApp(config=ast, mode=mode)
        
        # Setup the app first
        # print("[DEBUG] Before app.setup()") # Keep debug prints?
        await app.setup() # Assume setup handles passing mode down to teams
        # print("[DEBUG] After app.setup()")
        
        # Display available tools if in interactive mode
        if mode == "interactive":
            display_available_tools(app)
            logger.info("Starting interactive session")
            print(f"\nStarting interactive session with {app.name}")
            # print("[DEBUG] Before run_interactive_session()")
            await run_interactive_session(app)
            # print("[DEBUG] After run_interactive_session()")
            return True
        
        # Non-interactive mode
        elif input_text:
            logger.info(f"Running non-interactive workflow with initial input: {input_text}")
            # Find entry point team/lead
            entry_team = None
            entry_lead = None
            if app.teams:
                first_team_name = next(iter(app.teams))
                entry_team = app.teams[first_team_name]
                if hasattr(entry_team, 'lead') and entry_team.lead:
                    entry_lead = entry_team.lead
                else:
                    logger.error(f"Lead model not found for entry team '{first_team_name}'.")
                    console.print("[bold red]Error: Lead model not found for entry team.[/bold red]")
                    return False
            else:
                logger.error("No teams defined in the application.")
                console.print("[bold red]Error: No teams defined.[/bold red]")
                return False

            # How to start the non-interactive flow?
            # Option A: Call a method on the App like app.run_non_interactive(input_text)
            # Option B: Directly interact with the entry_team/entry_lead loop
            # Let's assume an app method for better encapsulation
            if hasattr(app, 'run_non_interactive'):
                final_response = await app.run_non_interactive(input_text)
                # Display final response
                if final_response:
                    console.print("\n[bold green]Final Response:[/bold green]")
                    console.print(final_response)
                else:
                    console.print("\n[bold yellow]Workflow completed, but no final response generated.[/bold yellow]")
                return True
            else:
                logger.error("Application does not support run_non_interactive method yet.")
                console.print("[bold red]Error: Non-interactive mode not fully implemented.[/bold red]")
                return False
        else:
            logger.error("Input text required for non-interactive mode")
            print("Error: Input text must be provided using --input for non-interactive mode.")
            return False
        
    except Exception as e:
        logger.error(f"Error running GLUE application: {e}", exc_info=True)
        print(f"\n[bold red]An unexpected error occurred:[/bold red] {e}")
        return False

async def run_interactive_session(app: GlueApp) -> None:
    """Run an interactive session with the GLUE application.
    
    Args:
        app: The GLUE application to run
    """
    logger = logging.getLogger("glue.interactive")
    console = Console()
    console.print("Type '/help' for commands, '/quit' to exit.")

    # Find the entry point team/lead
    entry_team: Optional[Team] = None
    entry_lead_loop: Optional[AgentLoop] = None
    if app.teams:
        first_team_name = next(iter(app.teams))
        entry_team = app.teams[first_team_name]
        if entry_team.lead:
             lead_loop_id = f"{entry_team.name}-lead-{entry_team.lead.name}"
             # Ensure loops are created
             if not entry_team.loop_coordinator or not entry_team.agent_loops:
                 logger.info("Creating agent loops before interactive session.")
                 await entry_team.create_agent_loops()
                 
             if lead_loop_id in entry_team.agent_loops:
                 entry_lead_loop = entry_team.agent_loops[lead_loop_id]
             else:
                 logger.error(f"Lead loop {lead_loop_id} not found after creation!")
        else:
            logger.error(f"Entry team '{first_team_name}' has no lead defined.")
    
    if not entry_lead_loop:
         console.print("[bold red]Error: Cannot start interactive session. Entry point lead model/loop not found.[/bold red]")
         return

    # --- Main Interactive Loop ---
    is_running = False # Flag to track if a task is active
    active_task_id = None
    
    while True:
        prompt_message = "GLUE> "
        current_lead_state = entry_lead_loop.get_status().get("state")
        
        # Check if the system is waiting for clarification (Placeholder check)
        # A more robust way would involve specific messages or states
        if is_running and current_lead_state == AgentState.WAITING: # Crude check
            # Check if team lead is waiting for user input - needs better signalling
            # For now, assume any WAITING state might need clarification if task is active
            prompt_message = "[bold yellow]Clarification Needed> [/bold yellow] " # Change prompt
            console.print("[yellow]The system is paused, awaiting clarification. Enter your query or type '/status' to check.[/yellow]")
        elif is_running:
             prompt_message = f"GLUE (Running Task {active_task_id})> "
             # Add periodic status check/update display here?
             # console.print(f"[dim]Lead state: {current_lead_state}[/dim]") # Example status
             
        try:
            user_input = Prompt.ask(prompt_message)
        except KeyboardInterrupt:
            console.print("\nExiting...")
            break # Exit on Ctrl+C
        except EOFError:
            console.print("\nExiting...")
            break # Exit on Ctrl+D

        user_input = user_input.strip()
        if not user_input:
            continue
                
        # --- Handle Commands --- 
        if user_input.lower() == "/quit":
            console.print("Exiting interactive session.")
            # Terminate loops gracefully?
            if entry_team and entry_team.loop_coordinator:
                 await entry_team.terminate_agent_loops(reason="user_quit")
            break
        elif user_input.lower() == "/help":
            console.print(get_interactive_help_text()) # Assuming this helper exists
            continue
        elif user_input.lower().startswith("/status"):
            # Display status of lead and agents
            if entry_team:
                console.print(f"[bold]Status for Team: {entry_team.name}[/bold]")
                status = entry_team.get_agent_status() # Get all statuses
                console.print(json.dumps(status, indent=2))
            else:
                console.print("[yellow]No active team to get status from.[/yellow]")
            continue
        elif user_input.lower().startswith("/pause"):
             # --- User initiated pause/clarification --- 
             if not is_running:
                 console.print("[yellow]No task is currently running to pause.[/yellow]")
                 continue
                 
             # Ensure there is text after /pause
             if len(user_input) <= len("/pause") or not user_input[len("/pause"):].strip():
                 console.print("[yellow]Usage: /pause <your query for clarification>[/yellow]")
                 continue
                 
             query = user_input[len("/pause"):].strip()
                  
             console.print(f"Broadcasting pause query: {query}")
             # Use the team's broadcast method
             if entry_team:
                 await entry_team.broadcast_pause_query(query)
             else:
                  logger.error("Cannot broadcast pause, no entry_team found.")
             continue # Wait for system to potentially enter HOLD/WAITING

        # --- Handle Regular Input (Task Submission or Clarification Response) ---
        if is_running and current_lead_state == AgentState.WAITING:
            # Assume this input is the clarification
            console.print(f"Sending clarification: {user_input}")
            # How to send this back? Needs a specific mechanism.
            # Option: Send message to lead loop via team queue?
            clarification_msg = {
                 "type": "user_clarification",
                 "content": user_input,
                 "task_id": active_task_id
            }
            if entry_team:
                 await entry_team.message_queue.put({"target_loop_id": entry_lead_loop.agent_id, "content": clarification_msg})
                 # Assume lead loop handles this message type
            else:
                 logger.error("Cannot send clarification, no entry_team found.")
            # The system should resume after lead processes clarification
            
        elif not is_running:
            # Assume this is a new task submission
            console.print(f"Starting new task with input: {user_input}")
            is_running = True
            active_task_id = f"interactive_{str(uuid.uuid4())[:8]}"
            
            # Define the initial task data for the lead
            initial_task_data = {
                "task_id": active_task_id,
                "goal": user_input,
                "adhesive": AdhesiveType.GLUE, # Default to Glue for final interactive output?
                "metadata": {"interactive_session": True}
            }
            
            # Start the lead loop in the background
            # We don't await here, allowing the UI loop to continue
            asyncio.create_task(entry_lead_loop.start(task_data=initial_task_data))
            console.print(f"Task {active_task_id} started in background.")
            
        else: # Input while running but not waiting for clarification
            console.print("[yellow]A task is already running. Use /pause <query> or wait for completion/clarification prompt.[/yellow]")

    logger.info("Interactive session ended.")

def display_available_tools(app: GlueApp) -> None:
    """Display the available tools in the GLUE application.
    
    Args:
        app: The GLUE application
    """
    print("\nAvailable tools:")
    # Implementation depends on how tools are stored in the app
    for tool_name, tool in app.tools.items():
        if isinstance(tool, dict):
            description = tool.get("description", "No description available")
        else:
            description = getattr(tool, "description", "No description available")
        print(f"  {tool_name} - {description}")

# ==================== Logging Setup ====================
def setup_logging(level=logging.INFO):
    """Set up logging configuration"""
    # Ensure log directory exists
    os.makedirs(LOGS_DIR, exist_ok=True)
    
    logging.basicConfig(
        level=level,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(os.path.join(LOGS_DIR, "glue.log"), mode='a')
        ]
    )
    
    # Create logger
    logger = logging.getLogger("glue")
    logger.setLevel(level)
    
    return logger

# ... (rest of the code remains the same)

# ==================== Project Management Functions ====================
def get_template_content(template: str, project_name: str) -> str:
    """Get the content for a template GLUE file.
    
    Args:
        template: Template type (basic, research, chat, or agent)
        project_name: Name of the project
        
    Returns:
        Content for the GLUE file
    """
    if template == "basic":
        return f"""glue app {{
    name = "{project_name}"
    config {{
        development = true
    }}
}}

// Define models
model assistant {{
    provider = openrouter
    role = "Help the user with their tasks"
    adhesives = [glue, velcro]
    config {{
        model = "meta-llama/llama-3.1-8b-instruct:free"
        temperature = 0.7
    }}
}}

// Define teams
magnetize {{
    main {{
        lead = assistant
    }}
}}

apply glue
"""
    elif template == "research":
        return f"""glue app {{
    name = "{project_name}"
    config {{
        development = true
        sticky = true
    }}
}}

// Define tools
tool web_search {{
    provider = serp
}}

tool file_handler {{
    config {{
        base_path = "./workspace"
    }}
}}

// Define models
model researcher {{
    provider = openrouter
    role = "You are a research assistant that helps the user find and analyze information."
    adhesives = [glue, velcro]
    config {{
        model = "meta-llama/llama-3.1-8b-instruct:free"
        temperature = 0.5
    }}
}}

// Define teams
magnetize {{
    research_team {{
        lead = researcher
        tools = [web_search, file_handler]
    }}
}}

apply glue
"""
    elif template == "chat":
        return f"""glue app {{
    name = "{project_name}"
    config {{
        development = true
    }}
}}

// Define models
model chat_assistant {{
    provider = openrouter
    role = "You are a helpful, friendly chat assistant."
    adhesives = [glue, velcro]
    config {{
        model = "meta-llama/llama-3.1-8b-instruct:free"
        temperature = 0.8
    }}
}}

// Define teams
magnetize {{
    chat {{
        lead = chat_assistant
    }}
}}

apply glue
"""
    elif template == "agent":
        return f"""glue app {{
    name = "{project_name}"
    config {{
        development = true
    }}
}}

// Define tools
tool web_search {{
    provider = serp
}}

tool file_handler {{
    config {{
        base_path = "./workspace"
    }}
}}

tool code_interpreter {{}}

// Define models
model agent {{
    provider = openrouter
    role = "You are an autonomous agent that can use tools to accomplish tasks."
    adhesives = [glue, velcro]
    config {{
        model = "meta-llama/llama-3.1-8b-instruct:free"
        temperature = 0.7
    }}
}}

// Define teams
magnetize {{
    agent_team {{
        lead = agent
        tools = [web_search, file_handler, code_interpreter]
    }}
}}

apply glue
"""
    else:
        return f"""glue app {{
    name = "{project_name}"
    config {{
        development = true
    }}
}}

// Define models
model assistant {{
    provider = openrouter
    role = "Help the user with their tasks"
    adhesives = [glue, velcro]
    config {{
        model = "meta-llama/llama-3.1-8b-instruct:free"
        temperature = 0.7
    }}
}}

// Define teams
magnetize {{
    main {{
        lead = assistant
    }}
}}

apply glue
"""

def create_new_project(project_name: str, template: str = "basic"):
    """Create a new GLUE project with template files.
    
    Args:
        project_name: Name of the project to create
        template: Template type to use (basic, research, chat, or agent)
    """
    logger = logging.getLogger("glue.create_project")
    
    # Create project directory
    project_dir = Path(project_name)
    if project_dir.exists():
        logger.error(f"Project directory '{project_name}' already exists")
        print(f"Error: Project directory '{project_name}' already exists")
        return False
    
    # Create project structure
    try:
        logger.info(f"Creating project '{project_name}' with template '{template}'")
        project_dir.mkdir(parents=True)
        
        # Create app.glue file
        app_content = get_template_content(template, project_name)
        (project_dir / "app.glue").write_text(app_content)
        
        # Create workspace directory
        (project_dir / "workspace").mkdir()
        
        # Create README.md
        readme_content = f"""# {project_name}

A GLUE framework application.

## Getting Started

1. Install the GLUE framework:
   ```
   pip install glue-framework
   ```

2. Run the application:
   ```
   glue run app.glue
   ```

## Configuration

Edit the `app.glue` file to customize your application.
"""
        (project_dir / "README.md").write_text(readme_content)
        
        # Create .env file with example settings
        env_content = """# API Keys for model providers
# OPENAI_API_KEY=your_openai_key
# ANTHROPIC_API_KEY=your_anthropic_key
# OPENROUTER_API_KEY=your_openrouter_key

# API Keys for tools
# SERP_API_KEY=your_serp_key
# TAVILY_API_KEY=your_tavily_key

# Portkey integration (optional)
# PORTKEY_ENABLED=true
# PORTKEY_API_KEY=your_portkey_key
"""
        (project_dir / ".env").write_text(env_content)
        
        # Create .gitignore
        gitignore_content = """# Environment variables
.env

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Workspace files (may contain sensitive data)
workspace/
"""
        (project_dir / ".gitignore").write_text(gitignore_content)
        
        logger.info(f"Project '{project_name}' created successfully")
        print(f"Project '{project_name}' created successfully in '{project_dir.absolute()}'")
        print(f"To run your application: cd {project_name} && glue run app.glue")
        return True
        
    except Exception as e:
        logger.error(f"Error creating project: {str(e)}")
        print(f"Error creating project: {str(e)}")
        return False

# ... (rest of the code remains the same)

# ==================== Forge Functions ====================
def forge_tool(name: str, description: str, template: str = "basic"):
    """Create a new custom tool.
    
    Args:
        name: Name of the tool
        description: Description of what the tool does
        template: Template type to use (basic, api, or data)
        
    Returns:
        bool: True if successful, False otherwise
    """
    logger = logging.getLogger("glue.forge_tool")
    
    # Validate name
    if not re.match(r'^[a-zA-Z][a-zA-Z0-9_]*$', name):
        logger.error(f"Invalid tool name: {name}. Must start with a letter and contain only letters, numbers, and underscores.")
        print(f"Error: Invalid tool name. Must start with a letter and contain only letters, numbers, and underscores.")
        return False
    
    # Create tools directory if it doesn't exist
    tools_dir = Path("tools")
    tools_dir.mkdir(exist_ok=True)
    
    # Create tool file
    tool_file = tools_dir / f"{name}.py"
    if tool_file.exists():
        logger.error(f"Tool file '{tool_file}' already exists")
        print(f"Error: Tool file '{tool_file}' already exists")
        return False
    
    # Generate tool code based on template
    if template == "basic":
        tool_code = f"""from glue.tools import SimpleBaseTool

class {name.capitalize()}Tool(SimpleBaseTool):
    \"\"\"
    {description}
    \"\"\"
    
    def __init__(self):
        super().__init__(
            name="{name}",
            description="{description}",
            parameters={{
                "type": "object",
                "properties": {{
                    "query": {{
                        "type": "string",
                        "description": "The input for the tool"
                    }}
                }},
                "required": ["query"]
            }}
        )
    
    async def _execute(self, query: str, **kwargs):
        \"\"\"
        Execute the tool with the given query.
        
        Args:
            query: The input for the tool
            **kwargs: Additional arguments
            
        Returns:
            The result of the tool execution
        \"\"\"
        # Implement your tool logic here
        return f"Executed {{self.name}} with query: {{query}}"

# Register the tool with the framework
def get_tool():
    return {name.capitalize()}Tool()
"""
    elif template == "api":
        tool_code = f"""import aiohttp
from glue.tools import SimpleBaseTool

class {name.capitalize()}Tool(SimpleBaseTool):
    \"\"\"
    {description}
    \"\"\"
    
    def __init__(self):
        super().__init__(
            name="{name}",
            description="{description}",
            parameters={{
                "type": "object",
                "properties": {{
                    "query": {{
                        "type": "string",
                        "description": "The query to send to the API"
                    }}
                }},
                "required": ["query"]
            }}
        )
        self.api_key = None
        self.base_url = "https://api.example.com"  # Replace with actual API URL
    
    async def setup(self):
        \"\"\"Set up the tool with API key from environment variables if not provided.\"\"\"
        import os
        self.api_key = os.environ.get("{name.upper()}_API_KEY")
        if not self.api_key:
            print(f"Warning: {name.upper()}_API_KEY not found in environment variables")
    
    async def _execute(self, query: str, **kwargs):
        \"\"\"
        Execute the tool by making an API request.
        
        Args:
            query: The query to send to the API
            **kwargs: Additional arguments
            
        Returns:
            The API response
        \"\"\"
        if not self.api_key:
            return "Error: API key not configured"
        
        headers = {{"Authorization": f"Bearer {{self.api_key}}"}}
        
        async with aiohttp.ClientSession() as session:
            async with session.get(
                f"{{self.base_url}}/search",
                params={{"q": query}},
                headers=headers
            ) as response:
                if response.status == 200:
                    data = await response.json()
                    return data
                else:
                    return f"Error: API returned status {{response.status}}"

# Register the tool with the framework
def get_tool():
    return {name.capitalize()}Tool()
"""
    elif template == "data":
        tool_code = f"""import pandas as pd
from glue.tools import SimpleBaseTool

class {name.capitalize()}Tool(SimpleBaseTool):
    \"\"\"
    {description}
    \"\"\"
    
    def __init__(self):
        super().__init__(
            name="{name}",
            description="{description}",
            parameters={{
                "type": "object",
                "properties": {{
                    "data_path": {{
                        "type": "string",
                        "description": "Path to the data file"
                    }},
                    "query": {{
                        "type": "string",
                        "description": "Query to filter or analyze the data"
                    }}
                }},
                "required": ["data_path", "query"]
            }}
        )
    
    async def _execute(self, data_path: str, query: str, **kwargs):
        \"\"\"
        Execute the tool by analyzing data.
        
        Args:
            data_path: Path to the data file
            query: Query to filter or analyze the data
            **kwargs: Additional arguments
            
        Returns:
            Analysis results
        \"\"\"
        try:
            # Load data based on file extension
            if data_path.endswith('.csv'):
                df = pd.read_csv(data_path)
            elif data_path.endswith('.xlsx') or data_path.endswith('.xls'):
                df = pd.read_excel(data_path)
            elif data_path.endswith('.json'):
                df = pd.read_json(data_path)
            else:
                return f"Unsupported file format: {{data_path}}"
            
            # Basic query processing - in a real tool, you'd implement more sophisticated analysis
            if "count" in query.lower():
                return f"Row count: {{len(df)}}"
            elif "columns" in query.lower():
                return f"Columns: {{', '.join(df.columns.tolist())}}"
            elif "summary" in query.lower() or "describe" in query.lower():
                return df.describe().to_string()
            else:
                # Default to returning the first few rows
                return df.head().to_string()
                
        except Exception as e:
            return f"Error processing data: {{str(e)}}"

# Register the tool with the framework
def get_tool():
    return {name.capitalize()}Tool()
"""
    else:
        logger.error(f"Unknown tool template: {template}")
        print(f"Error: Unknown tool template: {template}")
        return False
    
    # Write tool file
    tool_file.write_text(tool_code)
    
    # Create __init__.py if it doesn't exist
    init_file = tools_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Custom tools package\n")
    
    logger.info(f"Tool '{name}' created successfully")
    print(f"Tool '{name}' created successfully in '{tool_file}'")
    print(f"To use this tool, add the following to your app.glue file:")
    print(f"""
tool {name} {{
    custom = true
}}
""")
    return True

def forge_mcp(name: str, description: str):
    """Create a new MCP (Model Control Protocol) integration.
    
    Args:
        name: Name of the MCP integration
        description: Description of the MCP integration
        
    Returns:
        bool: True if successful, False otherwise
    """
    logger = logging.getLogger("glue.forge_mcp")
    
    # Validate name
    if not re.match(r'^[a-zA-Z][a-zA-Z0-9_]*$', name):
        logger.error(f"Invalid MCP name: {name}. Must start with a letter and contain only letters, numbers, and underscores.")
        print(f"Error: Invalid MCP name. Must start with a letter and contain only letters, numbers, and underscores.")
        return False
    
    # Create mcps directory if it doesn't exist
    mcps_dir = Path("mcps")
    mcps_dir.mkdir(exist_ok=True)
    
    # Create MCP file
    mcp_file = mcps_dir / f"{name}_mcp.py"
    if mcp_file.exists():
        logger.error(f"MCP file '{mcp_file}' already exists")
        print(f"Error: MCP file '{mcp_file}' already exists")
        return False
    
    # Generate MCP code
    mcp_code = f"""from typing import Dict, List, Any, Optional
from glue.core.mcp import BaseMCP

class {name.capitalize()}MCP(BaseMCP):
    \"\"\"
    {description}
    \"\"\"
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__(name="{name}", config=config or {{}})
        self.base_url = self.config.get("base_url", "https://api.example.com")
        self.api_key = self.config.get("api_key")
    
    async def setup(self):
        \"\"\"Set up the MCP with API key from environment variables if not provided.\"\"\"
        if not self.api_key:
            import os
            self.api_key = os.environ.get("{name.upper()}_API_KEY")
            if not self.api_key:
                print(f"Warning: {name.upper()}_API_KEY not found in environment variables")
    
    async def execute_function(self, function_name: str, arguments: Dict[str, Any]) -> Any:
        \"\"\"
        Execute a function through this MCP.
        
        Args:
            function_name: Name of the function to execute
            arguments: Arguments to pass to the function
            
        Returns:
            The result of the function execution
        \"\"\"
        # Implement your MCP function execution logic here
        # This is a placeholder implementation
        return {{
            "result": f"Executed {{function_name}} with arguments: {{arguments}}",
            "status": "success"
        }}
    
    async def get_available_functions(self) -> List[Dict[str, Any]]:
        \"\"\"
        Get a list of functions available through this MCP.
        
        Returns:
            List of function definitions
        \"\"\"
        # Return a list of function definitions
        # This is a placeholder implementation
        return [
            {{
                "name": "example_function",
                "description": "An example function",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "param1": {{
                            "type": "string",
                            "description": "First parameter"
                        }},
                        "param2": {{
                            "type": "integer",
                            "description": "Second parameter"
                        }}
                    }},
                    "required": ["param1"]
                }}
            }}
        ]

# Register the MCP with the framework
def get_mcp():
    return {name.capitalize()}MCP()
"""
    
    # Write MCP file
    mcp_file.write_text(mcp_code)
    
    # Create __init__.py if it doesn't exist
    init_file = mcps_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Custom MCPs package\n")
    
    logger.info(f"MCP '{name}' created successfully")
    print(f"MCP '{name}' created successfully in '{mcp_file}'")
    print(f"To use this MCP, add the following to your app.glue file:")
    print(f"""
mcp {name} {{
    custom = true
}}
""")
    return True

def forge_api(name: str, description: str):
    """Create a new API integration.
    
    Args:
        name: Name of the API integration
        description: Description of the API integration
        
    Returns:
        bool: True if successful, False otherwise
    """
    logger = logging.getLogger("glue.forge_api")
    
    # Validate name
    if not re.match(r'^[a-zA-Z][a-zA-Z0-9_]*$', name):
        logger.error(f"Invalid API name: {name}. Must start with a letter and contain only letters, numbers, and underscores.")
        print(f"Error: Invalid API name. Must start with a letter and contain only letters, numbers, and underscores.")
        return False
    
    # Create apis directory if it doesn't exist
    apis_dir = Path("apis")
    apis_dir.mkdir(exist_ok=True)
    
    # Create API file
    api_file = apis_dir / f"{name}_api.py"
    if api_file.exists():
        logger.error(f"API file '{api_file}' already exists")
        print(f"Error: API file '{api_file}' already exists")
        return False
    
    # Generate API code
    api_code = f"""import aiohttp
from typing import Dict, Any, Optional

class {name.capitalize()}API:
    \"\"\"
    {description}
    \"\"\"
    
    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        self.api_key = api_key
        self.base_url = base_url or "https://api.example.com"  # Replace with actual API URL
    
    async def setup(self):
        \"\"\"Set up the API client with API key from environment variables if not provided.\"\"\"
        if not self.api_key:
            import os
            self.api_key = os.environ.get("{name.upper()}_API_KEY")
            if not self.api_key:
                print(f"Warning: {name.upper()}_API_KEY not found in environment variables")
    
    async def get(self, endpoint: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        \"\"\"
        Make a GET request to the API.
        
        Args:
            endpoint: API endpoint
            params: Query parameters
            
        Returns:
            API response
        \"\"\"
        if not self.api_key:
            return {{"error": "API key not configured"}}
        
        headers = {{"Authorization": f"Bearer {{self.api_key}}"}}
        
        async with aiohttp.ClientSession() as session:
            async with session.get(
                f"{{self.base_url}}/{{endpoint}}",
                params=params,
                headers=headers
            ) as response:
                if response.status == 200:
                    return await response.json()
                else:
                    return {{
                        "error": f"API returned status {{response.status}}",
                        "status": response.status
                    }}
    
    async def post(self, endpoint: str, data: Dict[str, Any]) -> Dict[str, Any]:
        \"\"\"
        Make a POST request to the API.
        
        Args:
            endpoint: API endpoint
            data: Request data
            
        Returns:
            API response
        \"\"\"
        if not self.api_key:
            return {{"error": "API key not configured"}}
        
        headers = {{
            "Authorization": f"Bearer {{self.api_key}}",
            "Content-Type": "application/json"
        }}
        
        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{{self.base_url}}/{{endpoint}}",
                json=data,
                headers=headers
            ) as response:
                if response.status in (200, 201):
                    return await response.json()
                else:
                    return {{
                        "error": f"API returned status {{response.status}}",
                        "status": response.status
                    }}

# Create an instance of the API client
def get_api_client(api_key: Optional[str] = None, base_url: Optional[str] = None):
    return {name.capitalize()}API(api_key, base_url)
"""
    
    # Write API file
    api_file.write_text(api_code)
    
    # Create __init__.py if it doesn't exist
    init_file = apis_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Custom APIs package\n")
    
    logger.info(f"API '{name}' created successfully")
    print(f"API '{name}' created successfully in '{api_file}'")
    print(f"To use this API in your application:")
    print(f"""
from apis.{name}_api import get_api_client

# In an async function:
api_client = get_api_client()
await api_client.setup()
result = await api_client.get("endpoint", {{"param": "value"}})
""")
    return True

def run_forge_command():
    """Run the GLUE Forge interactive CLI to create custom components using Google Gemini.
    
    This function implements an interactive CLI that guides users through setting up
    their API key for Google Gemini and using it to create custom components.
    """
    import os
    import re
    import json
    import getpass
    from pathlib import Path
    
    logger = logging.getLogger("glue.forge")
    
    # ASCII art banner
    banner = """
  ██████  ██      ██    ██ ███████     ███████  ██████  ██████   ██████  ███████ 
 ██       ██      ██    ██ ██          ██      ██    ██ ██   ██ ██       ██      
 ██   ███ ██      ██    ██ █████       █████   ██    ██ ██████  ██   ███ █████   
 ██    ██ ██      ██    ██ ██          ██      ██    ██ ██   ██ ██    ██ ██      
  ██████  ███████  ██████  ███████     ██       ██████  ██   ██  ██████  ███████ 
                                                                                 
"""
    print(banner)
    print("Welcome to GLUE Forge - Create custom components with AI assistance")
    print("=" * 70)
    print("\nGLUE Forge uses Google Gemini 2.5 Pro, which is currently free to use.")
    print("You'll need an API key from either Google AI Studio or OpenRouter.")
    
    # Check if API key is already configured
    config_dir = Path(os.path.expanduser("~/.glue"))
    config_dir.mkdir(exist_ok=True)
    
    forge_config_file = config_dir / "forge_config.json"
    api_key = None
    api_source = None
    model_name = None
    
    if forge_config_file.exists():
        try:
            with open(forge_config_file, "r") as f:
                config = json.load(f)
                api_key = config.get("api_key")
                api_source = config.get("api_source")
                model_name = config.get("model_name")
                
            print(f"\nFound existing configuration: Using {api_source} API key")
            use_existing = input("Would you like to use this configuration? (Y/n): ").strip().lower()
            
            if use_existing != "n":
                print(f"Using existing {api_source} API key")
            else:
                api_key = None
                api_source = None
                model_name = None
        except Exception as e:
            logger.error(f"Error reading forge config: {str(e)}")
            print("Error reading existing configuration. Setting up new configuration.")
            api_key = None
            api_source = None
            model_name = None
    
    # If no API key is configured, prompt for one
    if not api_key:
        print("\nYou need an API key to use GLUE Forge. Choose your API key source:")
        print("1. Google AI Studio (https://makersuite.google.com/app/apikey)")
        print("2. OpenRouter (https://openrouter.ai/keys)")
        
        choice = None
        while choice not in ["1", "2"]:
            choice = input("\nEnter your choice (1 or 2): ").strip()
        
        if choice == "1":
            api_source = "Google AI Studio"
            model_name = "gemini-1.5-pro"
            print(f"\nGet your API key from: https://makersuite.google.com/app/apikey")
        else:
            api_source = "OpenRouter"
            model_name = "google/gemini-2.5-pro-exp-03-25:free"
            print(f"\nGet your API key from: https://openrouter.ai/keys")
        
        api_key = getpass.getpass(f"\nEnter your {api_source} API key: ").strip()
        
        # Validate API key format
        if not api_key or len(api_key) < 10:
            print("Invalid API key. Please provide a valid API key.")
            return False
        
        # Save configuration
        config = {
            "api_key": api_key,
            "api_source": api_source,
            "model_name": model_name
        }
        
        with open(forge_config_file, "w") as f:
            json.dump(config, f)
        
        print(f"\nAPI key saved. Using {api_source} with model: {model_name}")
    
    # Set the appropriate environment variable based on the API source
    if api_source == "Google AI Studio":
        os.environ["GOOGLE_API_KEY"] = api_key
    else:  # OpenRouter
        os.environ["OPENROUTER_API_KEY"] = api_key
    
    # Now run the forge command
    print("\nWhat would you like to create with GLUE Forge?")
    print("1. Custom Tool")
    print("2. Custom MCP Integration")
    print("3. Custom API Integration")
    
    forge_choice = None
    while forge_choice not in ["1", "2", "3"]:
        forge_choice = input("\nEnter your choice (1, 2, or 3): ").strip()
    
    if forge_choice == "1":
        name = input("\nEnter a name for your tool (letters, numbers, underscores only): ").strip()
        description = input("Enter a brief description of what your tool does: ").strip()
        
        print("\nChoose a template:")
        print("1. Basic Tool (simple function)")
        print("2. API Tool (makes external API calls)")
        print("3. Data Tool (processes data files)")
        
        template_choice = None
        while template_choice not in ["1", "2", "3"]:
            template_choice = input("\nEnter your choice (1, 2, or 3): ").strip()
        
        template = "basic" if template_choice == "1" else "api" if template_choice == "2" else "data"
        
        print(f"\nCreating {template} tool: {name}")
        forge_tool(name, description, template)
        
    elif forge_choice == "2":
        name = input("\nEnter a name for your MCP integration (letters, numbers, underscores only): ").strip()
        description = input("Enter a brief description of what your MCP integration does: ").strip()
        
        print(f"\nCreating MCP integration: {name}")
        forge_mcp(name, description)
        
    elif forge_choice == "3":
        name = input("\nEnter a name for your API integration (letters, numbers, underscores only): ").strip()
        description = input("Enter a brief description of what your API integration does: ").strip()
        
        print(f"\nCreating API integration: {name}")
        forge_api(name, description)
    
    print("\nThank you for using GLUE Forge!")
    return True

# ==================== Utility Functions ====================
def list_models():
    """List available models."""
    # Define available models by provider
    AVAILABLE_MODELS = {
        "openai": ["gpt-3.5-turbo", "gpt-4", "gpt-4-turbo"],
        "anthropic": ["claude-3-opus", "claude-3-sonnet", "claude-3-haiku"],
        "google": ["gemini-pro", "gemini-ultra"],
        "openrouter": ["meta-llama/llama-3.1-8b-instruct", "anthropic/claude-3-opus", "google/gemini-pro"]
    }
    
    print("Available models:")
    for provider, models in AVAILABLE_MODELS.items():
        print(f"\n{provider.capitalize()} Models:")
        for model in models:
            print(f"  - {model}")
            
def display_tools():
    """Display information about available tools to the console."""
    # Use the global AVAILABLE_TOOLS constant
    print("Available tools:")
    for tool_name, tool_info in AVAILABLE_TOOLS.items():
        print(f"\n{tool_name}:")
        print(f"  Description: {tool_info.get('description', 'No description')}")
        print(f"  Parameters: {tool_info.get('parameters', 'No parameters')}")
        
def validate_glue_file(config_file):
    """Validate a GLUE configuration file.
    
    Args:
        config_file: Path to the GLUE configuration file
    """
    logger = logging.getLogger("glue.validate")
    logger.info(f"Validating GLUE file: {config_file}")
    
    try:
        # Read the GLUE file
        with open(config_file, 'r') as f:
            glue_content = f.read()
        
        # Create lexer and parser
        from .dsl.lexer import GlueLexer
        from .dsl.parser import GlueDSLParser
        
        lexer = GlueLexer()
        parser = GlueDSLParser()
        
        # Parse the GLUE file
        tokens = lexer.tokenize(glue_content)
        ast = parser.parse(tokens)
        
        # If we get here, the file is valid
        print(f"✅ GLUE file {config_file} is valid")
        
        # Print some basic information about the configuration
        if "app" in ast:
            app_name = ast["app"].get("name", "Unnamed App")
            app_version = ast["app"].get("version", "Unknown Version")
            print(f"App: {app_name} (Version: {app_version})")
            
        if "models" in ast:
            print(f"Models: {len(ast['models'])}")
            
        if "tools" in ast:
            print(f"Tools: {len(ast['tools'])}")
            
        if "magnetize" in ast:
            print(f"Teams: {len(ast['magnetize'])}")
            
        if "flows" in ast:
            print(f"Flows: {len(ast['flows'])}")
            
    except Exception as e:
        print(f"❌ Error validating GLUE file: {e}")
        sys.exit(1)

# ==================== Main CLI Entry Point ====================
def main():
    """Main CLI entry point"""
    # Set up argument parser
    parser = argparse.ArgumentParser(
        description="GLUE Framework CLI - GenAI Linking & Unification Engine",
        formatter_class=argparse.RawTextHelpFormatter 
    )
    
    # --- Common Arguments --- 
    # Ensure verbose is defined *before* subparsers
    parser.add_argument("-v", "--verbose", action="count", default=0, 
                          help="Increase verbosity level (-v, -vv, -vvv).")
    
    # Create subparsers for commands
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # Run command
    run_parser = subparsers.add_parser("run", help="Run a GLUE application from a config file.")
    run_parser.add_argument("config_file", help="Path to the GLUE configuration file (.glue or .json).")
    run_parser.add_argument("--mode", choices=['interactive', 'non-interactive'], default='non-interactive', 
                            help="Execution mode (default: non-interactive)." )
    run_parser.add_argument("--input", help="Initial input text for non-interactive mode.")
    # Add verbose argument redundantly to run subparser as a workaround
    run_parser.add_argument("-v", "--verbose", action="count", default=0, 
                            help="Increase verbosity level (defined globally too)." )
    
    # Forge command (for creating custom components)
    forge_parser = subparsers.add_parser("forge", help="Create new GLUE components (tools, models, etc.).")
    forge_parser.add_argument("component_type", choices=['tool', 'mcp', 'api'], help="Type of component to forge.")
    forge_parser.add_argument("name", help="Name of the component to forge.")
    forge_parser.add_argument("-d", "--description", default="", help="Description for the component.")
    
    # Init command
    init_parser = subparsers.add_parser("init", help="Initialize a new GLUE project in the current directory.")
    init_parser.add_argument("project_name", nargs="?", default=os.path.basename(os.getcwd()), 
                             help="Name for the new project (default: current directory name).")
    init_parser.add_argument("--template", default="basic", help="Project template to use (default: basic).")
    
    # Validate command
    validate_parser = subparsers.add_parser("validate", help="Validate a GLUE configuration file.")
    validate_parser.add_argument("config_file", help="Path to the GLUE configuration file to validate.")
    
    # List command
    list_parser = subparsers.add_parser("list", help="List available components.")
    list_parser.add_argument("component", choices=['models', 'tools'], help="Component type to list.")
    
    # Version command
    subparsers.add_parser("version", help="Show GLUE framework version.")
    
    args = parser.parse_args()
    
    # Set up logging
    log_level = logging.WARNING
    if args.verbose == 1:
        log_level = logging.INFO
    elif args.verbose >= 2:
        log_level = logging.DEBUG
    setup_logging(log_level)
    logger = logging.getLogger("glue.cli")
    
    logger.debug(f"CLI arguments received: {args}")
    
    # Process commands
    exit_code = 0
    try:
        if args.command == "run":
            if not args.config_file:
                parser.error("The 'run' command requires a configuration file path.")
            if args.mode == 'non-interactive' and not args.input:
                parser.error("The 'run' command in non-interactive mode requires --input text.")
            
            success = asyncio.run(run_app(args.config_file, mode=args.mode, input_text=args.input))
            exit_code = 0 if success else 1
            
        elif args.command == "forge":
            # Placeholder for forge logic
            print(f"Forging {args.component_type}: {args.name}")
            if args.component_type == 'tool':
                forge_tool(args.name, args.description)
            elif args.component_type == 'mcp':
                forge_mcp(args.name, args.description)
            elif args.component_type == 'api':
                forge_api(args.name, args.description)
            else:
                print("Unknown component type to forge.")
                exit_code = 1
                
        elif args.command == "init":
            create_new_project(args.project_name, args.template)
            
        elif args.command == "validate":
            if not args.config_file:
                parser.error("The 'validate' command requires a configuration file path.")
            if validate_glue_file(args.config_file):
                print(f"[green]Validation successful: {args.config_file}[/green]")
            else:
                print(f"[red]Validation failed for: {args.config_file}[/red]")
                exit_code = 1
                
        elif args.command == "list":
            if args.component == "models":
                list_models()
            elif args.component == "tools":
                display_tools()
            else:
                parser.error("Invalid component type for list command.")
            
        elif args.command == "version":
            print(f"GLUE Framework Version: {__version__}")
            
        elif args.config_file: # Default action if config file is provided without command
            # Default to running in non-interactive mode if input is provided, else interactive?
            # Let's require explicit 'run' command for clarity.
            print("Please use the 'run' command to execute a configuration file.")
            parser.print_help()
            exit_code = 1
            
        else:
            parser.print_help()
            
    except Exception as e:
        logger.error(f"An error occurred during command execution: {e}", exc_info=True)
        print(f"\n[bold red]An unexpected error occurred:[/bold red] {e}")
        exit_code = 1
        
    sys.exit(exit_code)

if __name__ == "__main__":
    main()
