name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        # Remove the editable install line and install the package in development mode
        grep -v "^-e " requirements.txt > requirements_ci.txt
        pip install -r requirements_ci.txt
        pip install -e .
    - name: Lint with ruff
      run: |
        ruff check src tests
